version: "3.8"
services:
  backend:
    image: ousskh/backend-achat:latest
    ports:
      - "8089:8089"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/achatdb?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    networks:
      - mynetwork
    depends_on:
      - db

  frontend:
    image: ousskh/frontend-achat:latest
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - mynetwork

  db:
    container_name: database
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: AchatDb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge